### ISSUE TITLE
Can't run the game on Manjaro KDE

### ISSUE THREAD

**Issue by DTomArt** [MarcinDadura/Shamboogeon#43]
Hello!
After successfully installing necessary tools using 
`pip3 install pygame`
and
`pip3 install pygame-menu`
the game does not run on Manjaro KDE. The window with game appears and closes immediately. 

```
➜  Shamboogeon git:(master) python3 main.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.1.4
Traceback (most recent call last):
  File "/mnt/Zabawa/Shamboogeon/main.py", line 476, in <module>
    game_menu = Menu(screen, 'sounds/menu-theme-final.ogg')
  File "/mnt/Zabawa/Shamboogeon/classes/main_menu.py", line 30, in __init__
    self.menu = pygame_menu.Menu(600, 800, 'Shamboogeon',
  File "/home/tomart/.local/lib/python3.9/site-packages/pygame_menu/menu.py", line 227, in __init__
    assert isinstance(height, NumberInstance)
AssertionError
```
Please help, it looks epic and I want to play

**Comment by arczan2** [comment]
The problem is new version of pygame_menu library.
I'll fix it today :)
